### ISSUE TITLE
Report includes source maps

### ISSUE THREAD

**Issue by lord2800** [gregtillbrook/parcel-plugin-bundle-visualiser#15]
Is this intentional? My source maps are much larger than my actual output and crowd the screen out.

**Comment by gregtillbrook** [comment]
Thats an interesting one. The visualiser should only show files that are bundled (obviously) but it's representing a file list thats generated by parcel. Do you have an example project (that reproduces the problem) that I could look at?

**Comment by lord2800** [comment]
Not offhand, but I can strip one down.

**Comment by dgreensp** [comment]
Looking forward to the fix being released!

**Comment by orzechowskid** [comment]
the last `npm publish` for this package appears to be about a year ago.  would it be a huge bother to publish a new version of this package containing the fix for the issue described in this thread?  I'd love to be able to remove source maps from my reports without having to `npm install` straight from GitHub.

thanks!

**Comment by ykravv** [comment]
Actual code contains the fix for this case
File `src/buildTreeData.js` line 23: 
```
    if (child.name.endsWith('.map')) continue;
```

Seems, like code was not published to npm, and npm package is different from the master branch.

@gregtillbrook, could you please take a look and publish the latest version?

**Comment by ykravv** [comment]
@orzechowskid you can install from github via `npm i gregtillbrook/parcel-plugin-bundle-visualiser#master`

**Comment by virtualfunction** [comment]
@ykravv Thanks for this. 
I would argue it's probably best to ignore anything that's not a CSS or JS files (have I missed anything out) as I've got Font Awesome polluting my reports

Generally, I do think this needs to have the ability to config the plugin via a JSON file or package.json directive, not just with file types but if the report is generated (sometimes it's nice to know in dev what's taking up space, depending on workflow).

I gather though in Parcel 2 things will be shaken up and there will be a rewritten version of this plugin (I believe I saw evidence of this somewhere)
