### ISSUE TITLE
🙋Allow configuring of report output destination

### ISSUE THREAD

**Issue by gregtillbrook** [gregtillbrook/parcel-plugin-bundle-visualiser#2]
The report output location is currently fixed to `<project root>/report.html`. This has been fine for me but folks may want to specify the output location and report name. 

If this is a valuable feature for you then let me know here.

**Comment by Lugribossk** [comment]
It would be great if this could be configured, or perhaps followed the Parcel out-dir option. That way it doesn't clutter up the project root and won't need it's own .gitignore entry to avoid comitting it.

**Comment by jbreckmckye** [comment]
Why not just output the report in the `out-dir`, like @Lugribossk says? No config, but no root directory cluttering either.

**Comment by gregtillbrook** [comment]
Interesting idea - I wasn't aware of `out-dir` but will take a look. Cheers!

**Comment by simonlc** [comment]
For me this causes a problem since I run the bundler twice, but only care about the first report, so to get a report I have to specifically run only the first bundle alone. It would be nice if by default it would base the report name to something unique, or linked to the bundle entry point in some way.

**Comment by RPDeshaies** [comment]
Any status on this ?

**Comment by jbreckmckye** [comment]
PR for this: https://github.com/gregtillbrook/parcel-plugin-bundle-visualiser/pull/12

**Comment by gregtillbrook** [comment]
Thanks to @jbreckmckye  the `out-dir` solution is now in. So I'll consider this issue closed - for now, but I do intend to revisit when/if the parcel plugin overhaul happens.
