### ISSUE TITLE
Parcel 2 support

### ISSUE THREAD

**Issue by Ajaxy** [gregtillbrook/parcel-plugin-bundle-visualiser#26]
Does this plugin work with Parcel 2? No report.html is generated for me after switching Parcel from v1 to v2. Thanks!

**Comment by mischnic** [comment]
This is already implemented as a core plugin in Parcel 2 - invoking with the env variable `PARCEL_BUNDLE_ANALYZER=1` set should create a folder "parcel-bundle-reports".

https://github.com/parcel-bundler/parcel/blob/v2/packages/reporters/bundle-analyzer/src/BundleAnalyzerReporter.js#L15

**Comment by Ajaxy** [comment]
Thanks!
