### ISSUE TITLE
Consider dropping support for both 'visualise' and 'visualize'

### ISSUE THREAD

**Issue by davidnagli** [gregtillbrook/parcel-plugin-bundle-visualiser#5]
I realize that both of these are perfectly valid alternate spellings, but it generally makes it more confusing to use and document with both spellings.

Up to you.... just my two cents :)

**Comment by gregtillbrook** [comment]
I tend to like the idea of postel's law for interfaces - to be 'generous in what you accept but strict in what you produce' but I take your point about docs.

Ive changed the docs to only have '--visualise' but the 'zee' version will still be accepted if someone _really_ wants to use it.
