### ISSUE TITLE
error: unknown option `--visualise'

### ISSUE THREAD

**Issue by xDae** [gregtillbrook/parcel-plugin-bundle-visualiser#6]
I dont know what Im doing wrong, but i always get this message

**Comment by gregtillbrook** [comment]
what version of parcel are you using?

**Comment by gregtillbrook** [comment]
Not sure how long it'll take for the parcel change so Ive completely removed the `--visualise` cli arg for now.

Thanks for the heads up on the problem!

**Comment by xDae** [comment]
thanks @gregtillbrook !

**Comment by TimNZ** [comment]
ENV vars for a temp workaround?

**Comment by davidnagli** [comment]
@gregtillbrook Honestly I don't think the plugin overhaul will be done anytime soon. 😟 

As @TimNZ mentioned, env vars might be the only workaround for now 😬

**Comment by gregtillbrook** [comment]
@TimNZ ENV is an interesting workaround idea - Id rather not have the usage keep changing though so think I'll drop the `--visualise` bit for now and revisit when parcels updated. If it proves a nuisance and folks complain, i'll look at it again.

Thanks for the heads up @davidnagli

**Comment by TimNZ** [comment]
Plenty of tools support CLI and ENV for option setting, you can support both when CLI works?

**Comment by TimNZ** [comment]
Hi @davidnagli.  CLI vs ENV comment was for @gregtillbrook 
There are definitely other things the Parcel team should be prioritising. Thanks
